name: Tauri

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

    - uses: actions/checkout@v2
    - name: Install rust stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          
    - uses: actions/checkout@v3
    - name: install trunk
      run: |
          cargo install --locked trunk
          cargo install wasm-bindgen-cli
      
    - name: Build the app
      id: tauri_action
      uses: tauri-apps/tauri-action@dev

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
        releaseName: 'v__VERSION__' # tauri-action replaces \_\_VERSION\_\_ with the app version.
        releaseBody: 'See the assets to download and install this version.'
        releaseDraft: false
        prerelease: true

    - name: Upload exe file
      uses: actions/upload-artifact@v3
      with:
        name: wave_insight_tauri
        path: |
          target\release\*.exe
          target\release\wave_insight_tauri

    - name: Upload release assets windows
      if: matrix.platform == 'windows-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.tauri_action.outputs.releaseUploadUrl }}
        asset_path: target\release\wave_insight_tauri.exe
        asset_name: wave_insight_tauri.exe
        asset_content_type: application/vnd.microsoft.portable-executable

    - name: Upload release assets linux
      if: matrix.platform == 'ubuntu-20.04'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.tauri_action.outputs.releaseUploadUrl }}
        asset_path: target/release/wave-insight-tauri
        asset_name: wave_insight_tauri_ubuntu
        asset_content_type: application/octet-stream

    - name: Upload release assets mac
      if: matrix.platform == 'macos-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.tauri_action.outputs.releaseUploadUrl }}
        asset_path: target/release/wave_insight_tauri
        asset_name: wave_insight_tauri_mac
        asset_content_type: application/octet-stream
